// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvGph9juEwTVP3Mt5bAjPXFmN7XnOD5Q',
    appId: '1:241816291051:android:38dc2bea856e8b0af4a0ae',
    messagingSenderId: '241816291051',
    projectId: 'foodiesapp-6068c',
    storageBucket: 'foodiesapp-6068c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlM9n1nAwIYXOm5YljKMVGi80JVUEaEw',
    appId: '1:241816291051:ios:eab0bbb6ce726d35f4a0ae',
    messagingSenderId: '241816291051',
    projectId: 'foodiesapp-6068c',
    storageBucket: 'foodiesapp-6068c.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6D2RCpsHjHgsEt3--Bu72_jk__7XklY',
    appId: '1:241816291051:web:19f525634d73050ef4a0ae',
    messagingSenderId: '241816291051',
    projectId: 'foodiesapp-6068c',
    authDomain: 'foodiesapp-6068c.firebaseapp.com',
    storageBucket: 'foodiesapp-6068c.firebasestorage.app',
    measurementId: 'G-R845PDLYXD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArlM9n1nAwIYXOm5YljKMVGi80JVUEaEw',
    appId: '1:241816291051:ios:eab0bbb6ce726d35f4a0ae',
    messagingSenderId: '241816291051',
    projectId: 'foodiesapp-6068c',
    storageBucket: 'foodiesapp-6068c.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgot5m35BvDZqzbpUMsFslrjznBhZkYM',
    appId: '1:241816291051:web:46d5de5e861377e4f4a0ae',
    messagingSenderId: '241816291051',
    projectId: 'foodiesapp-6068c',
    authDomain: 'foodiesapp-6068c.firebaseapp.com',
    storageBucket: 'foodiesapp-6068c.firebasestorage.app',
    measurementId: 'G-0E1CQM3256',
  );
}
